import type { Trip, ItineraryDay, ItineraryItem, Expense, TripMember } from "@/lib/types";

export const DEMO_TRIPS: Trip[] = [
  {
    id: "demo-trip-1",
    name: "Japan Oct 2026",
    country: "Japan",
    startDate: new Date("2026-10-16"),
    endDate: new Date("2026-10-24"),
    budget: 150000,
    currency: "THB",
    createdAt: new Date(),
    updatedAt: new Date(),
    members: [],
    _count: { days: 9, expenses: 12 },
  },
  {
    id: "demo-trip-2",
    name: "Bangkok Weekend",
    country: "Thailand",
    startDate: new Date("2026-06-01"),
    endDate: new Date("2026-06-03"),
    budget: 15000,
    currency: "THB",
    createdAt: new Date(),
    updatedAt: new Date(),
    members: [],
    _count: { days: 3, expenses: 5 },
  },
];

export const DEMO_DAYS: ItineraryDay[] = [
  {
    id: "demo-day-1",
    tripId: "demo-trip-1",
    date: new Date("2026-10-16"),
    title: "Day 1 — Arrival in Nagoya",
    order: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    items: [
      {
        id: "demo-item-1",
        dayId: "demo-day-1",
        time: "08:00",
        title: "Airport → Hotel",
        notes: "Meitetsu Airport Express to Nagoya Station",
        category: "transport",
        amount: 1140,
        currency: "JPY",
        order: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "demo-item-2",
        dayId: "demo-day-1",
        time: "14:00",
        title: "Nagoya Castle",
        notes: "Book tickets in advance",
        category: "tickets",
        amount: 500,
        currency: "JPY",
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "demo-day-2",
    tripId: "demo-trip-1",
    date: new Date("2026-10-17"),
    title: "Day 2 — Shirakawa-go",
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    items: [
      {
        id: "demo-item-3",
        dayId: "demo-day-2",
        time: "09:00",
        title: "Bus to Shirakawa-go",
        notes: "Nohi Bus from Nagoya",
        category: "transport",
        amount: 3200,
        currency: "JPY",
        order: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];

export const DEMO_EXPENSES: Expense[] = [
  {
    id: "demo-exp-1",
    tripId: "demo-trip-1",
    title: "Hotel Mimatsu Awara Onsen",
    amount: 25000,
    currency: "JPY",
    baseAmount: 6250,
    baseCurrency: "THB",
    category: "hotel",
    date: new Date("2026-10-18"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-exp-2",
    tripId: "demo-trip-1",
    title: "Ramen Yamagishi",
    amount: 850,
    currency: "JPY",
    baseAmount: 212,
    baseCurrency: "THB",
    category: "food",
    date: new Date("2026-10-16"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-exp-3",
    tripId: "demo-trip-1",
    title: "JR Pass",
    amount: 50000,
    currency: "JPY",
    baseAmount: 12500,
    baseCurrency: "THB",
    category: "transport",
    date: new Date("2026-10-16"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
